services:
  - type: web
    name: ozan-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ozan_webhook_telegram.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "YOUR_TELEGRAM_BOT_TOKEN"
      - key: TELEGRAM_CHAT_ID
        value: "YOUR_TELEGRAM_CHAT_ID"